### ISSUE TITLE
Feature requests for this AMAZINGLY USEFUL plug-in

### ISSUE THREAD

**Issue by autonomygaps** [graydon/obsidian-dangling-links#1]
I love this plug-in.  This is a total game-changer!  It facilitates a workflow in which I can Wiki-wrap a key term when I'm writing or reviewing text in Obsidian, without stopping to flesh out a new note but with the confidence that there is a way to periodically review the "open loops" of "non-existent" files that look at later.  The graph view lets you do this, in a way, but this is so much faster and clearer.

Two feature requests, related to the fact that I currently have hundreds of dangling links: 
1. Folding by folders, like a bulleted outline, so that you can focus on the dangling links in a particular folder.
2. Sorting by Date Modified, Date Created, and Note Title. (Current it seems to be alpha order, but first by folder)

**Comment by flip-md** [comment]
Hey @graydon - thanks for this great plugin! I do have a couple of features I would like to see in this plugin (and from discussions it seems others do, too), and would like to inquire about how you would like to proceed here.
I can either start forming pull requests against your repo or fork/rewrite your plugin and keep on working from there. Do you have any preference here?

**Comment by graydon** [comment]
Oh hi @flip-md ! Sorry, just been busy. Um, I guess there are two implied questions here:

  - Will I accept PRs? Very likely! Unless they destroy the existing functionality, make a mess of the code or require a lot of time/energy to integrate (it's very little code anyway) I'm usually happy to accept contributions to anything I've written, publish updates, adjust URLs and READMEs, etc.
  - Will I allocate more time than just "PR integration & bare-bones maintenance" to work on adding new features? Maybe. Depends on the usual factors: how much I need the feature myself, how hard it is, and how much time I have free. At the moment the plugin is meeting my own needs, I have literally forgotten everything I learned to write the plugin in the first place (I'm not a typescript or even frontend dev at all), and I have exceptionally little free time this month, so at present this is unlikely. But I might be able to scrape some time up in another month or two.

Hope that answers your question! Glad it's useful to someone.

**Comment by flip-md** [comment]
@graydon thank you for the fast response! That is all I needed to hear, I will start working on it soon. I think nobody is in a hurry, your plugin served us well for half a year now. Have a good one, see you on my PR :)

**Comment by graydon** [comment]
Thanks @flip-md for handling the first part of this issue (grouping/folding) and asc/desc alpha sort order. I've split out the residual issue of date sorting as a secondary issue (#8), and am closing this one.

**Comment by autonomygaps** [comment]
Makes sense. Thanks for the great work on this!  Having collapsable folders make a world of difference for me.
