### ISSUE TITLE
Just feedback: Great usability & productivity boost!

### ISSUE THREAD

**Issue by Moonbase59** [graydon/obsidian-dangling-links#10]
No issue, just feedback:

This is something that should have been in Obsidian from Day One. I so often create lots of wikilinks when writing new notes, thinking to fill them in later, and could never find them again.

Thanks a bundle for making this! It really boosts usability and productivity enormously!

**Comment by claremacrae** [comment]
Thanks for the comment.

(For the avoidance of doubt, I'm not - yet - a developer here: I've been given permission to triage issues, so I'm going through closing things.)
