### ISSUE TITLE
Divide the list to subsections, with the first letter as each section's heading

### ISSUE THREAD

**Issue by Taitava** [graydon/obsidian-dangling-links#16]
Hi! I always use this plugin with the _Group by dangling link_ option selected, so all the links appear in a long list.

I have tens of dangling links in the list. If I want to find a specific dangling link, I need to scroll through the long list (which is ok to me) and keep an eye on the alphabetical order to spot when the links start to beging with the same letter as the link I'm looking for.

E.g. If I'm looking for a link named _Work_, I'll scroll the list fast until I reach links that begin with _W_, then I continue scrolling slowly to find the one I'm looking for. Fast scrolling would be easier if the list was divided into sublists, each list containing links that begin with a certain letter. So every time the first letter changes in the list of links, add some space and a heading with the next links' first letter as the heading text.

**Comment by claremacrae** [comment]
Hi @Taitava,

> I have tens of dangling links in the list. If I want to find a specific dangling link,

Could you please say why - in what situation or circumstance - you need to find a **specific** dangling link, and why you need to do it frequently enough for someone to need to write a new feature for you?

What's stopping you fixing one dangling link at a time until you have few enough that it isn't onerous to find a specific one?

Many thanks.

**Comment by claremacrae** [comment]
Also, the workaround is a great idea! 💡

**Comment by Taitava** [comment]
My use-case is that I'm writing about many different subjects in my personal life, and as I write, I make some of the words I to be dangling links. Each dangling link represents a possible future subject/idea for me to write about. Currently, I have about 450 dangling links, which I can admit to be actually too much. I will never write about all of them, and I could actually go through them and remove links from words that I will probably never write a separate page for.

So, my aim is not to get all the dangling links removed by writing a note for each one them, but instead the list works for me as a place for ideas that I _could_ write about. Many times when I'm about to create a new dangling link (= surround some word in my text with `[[` and `]]`), I go through the list of the current dangling links and look if that word (or a synonym) happens to be there already. If there is a synonym or almost similar word, I will not create a new dangling link.

I guess my workflow differs quite a lot from a typical use-case where users will actually want to "fix" all their dangling links. In that light I do understand that maybe this "subsections" feature of mine would not serve many users and so is perhaps not worth implementing. 👍

**Comment by claremacrae** [comment]
Hi @Taitava,

Thank you for this and all your other helpful answers.

This does explain your situation well.

> I guess my workflow differs quite a lot from a typical use-case where users will actually want to "fix" all their dangling links. In that light I do understand that maybe this "subsections" feature of mine would not serve many users and so is perhaps not worth implementing. 👍

Thank you for being so understanding.

I do agree that because:

- as your goal is not to resolve all your dangling links and so you have very many of them,
- and you have also found a rather clever workaround...

... this change is unlikely to a high enough priority to be implemented.
