### ISSUE TITLE
Black Screen on click on dangling link

### ISSUE THREAD

**Issue by vincent456** [graydon/obsidian-dangling-links#18]
When clicking a dangling link from the dangling link panel, obsidian turn into a black screen.
Tested on Obsidian v0.14.4
No Error in the console

**Comment by claremacrae** [comment]
@vincent456 I get this, except that I get a white screen. I'm using a light theme...

Tested with:
- Obsidian v0.14.7
- Installer 0.12.15
- Dangling links 0.3.0

Vault status:

- No other plugins enabled
- Default theme
- No snippets enabled

I did get this in the console, when I displayed it before clicking on a dangling link in the dangling link panel:

> app.js:1 Obsidian Developer Console
> app.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> app.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by claremacrae** [comment]
It gives the white screen in all of:

New editor

- Reading view
- Source mode
- Live preview mode

Legacy Editor

- Reading view
- Source mode

**Comment by claremacrae** [comment]
Hi @graydon Thank you for this useful plugin!

FYI Unfortunately this issue renders the plugin completely non-functional on the current Obsidian.

The only workaround I've found is to have the plugin pane visible, and then manually open each page with the dangling links and search for the dangling link...

**Comment by Superfeuchter** [comment]
same problem ...

Obsidian v0.14.7

It's such a useful plugin, so I check the dangling links manually instead of klick on them.
I wish there'd be a solution some time, because it's great.

**Comment by graydon** [comment]
Apologies, I haven't been able to work on this plugin for the past while -- I'll try to get to updating it with at least minimal bug fixes soon. Meanwhile I'd be happy to accept patches to fix such things.

**Comment by claremacrae** [comment]
> I have just tested this with current Obsidian version 0.14.15 and the issue does not appear anymore.

Confirmed. Thanks very much for sharing that great news!

**Comment by Superfeuchter** [comment]
Oh fine, it works again with v.0.14.15 - Test successful!
Thanks a lot!

**Comment by claremacrae** [comment]
> Oh fine, it works again with v.0.14.15 - Test successful! Thanks a lot!
