### ISSUE TITLE
Error Message on Developer Console

### ISSUE THREAD

**Issue by adxsoft** [graydon/obsidian-dangling-links#2]
Hi
Thanks for this very useful plugin.
I'm using Obsidian 0.9.17 and noticed this error message in the Developer Console

![Screen Shot 2020-12-12 at 4 32 29 pm](https://user-images.githubusercontent.com/24862237/101976370-b720ae80-3c98-11eb-8784-df564d806ba1.png)

the plugin still seems to work well but I though I'd bring this error message to your attention

Cheers
Allan @ adxsoft

**Comment by flip-md** [comment]
Should be addressed in in https://github.com/graydon/obsidian-dangling-links/pull/7 and hopefully merged soon :)

**Comment by graydon** [comment]
Merged and released in 0.3.0
