### ISSUE TITLE
Include dangling header links

### ISSUE THREAD

**Issue by mitchnolte** [graydon/obsidian-dangling-links#20]
I really like the idea of this plugin but it currently doesn't do much for me, because usually my links go to a header within a file rather than just the whole file, and the plugin only seems to recognize links as dangling if the file itself doesn't exist. There's often times when I change a header name or something and obsidian doesn't automatically update links to headers in this situation like it does for links to files, so any links to those headers become dangling. I was hoping this plugin could find those dangling links to old headings but it doesn't unless the file it points to doesn't exist either. I also often link to headers within the file I'm linking from, so these would never be detected if the header changes because it's pointing to the file it's written in which would obviously still exist as long as the link did.

As a side note I also have the same issue as #15. When I open the dangling link view I want it to go to the one I already have open, but it currently just opens a new one every time.

**Comment by claremacrae** [comment]
Thanks for the suggestion. I very much agree this would be good functionality.

I see this is reporting the same as #6, so I'll close this one.
