### ISSUE TITLE
PLugin uninstalled but still seeing Dangling Links panes

### ISSUE THREAD

**Issue by bongoman** [graydon/obsidian-dangling-links#21]
<img width="212" alt="Screen Shot 2022-12-03 at 8 48 38 pm" src="https://user-images.githubusercontent.com/75063/205436084-a095d9b8-7368-4b56-b535-eaf12d0987ff.png">

**Comment by claremacrae** [comment]
That is normal Obsidian behaviour when a Plugin has been removed or disabled and its pane was still open.

It can be useful of you temporarily turn a plugin off, or run in safer mode, to test something... and then later turn the plugin(s) back on.

**Comment by claremacrae** [comment]
> That is normal Obsidian behaviour when a Plugin has been removed or disabled and its pane was still open.
> 
> It can be useful of you temporarily turn a plugin off, or run in safer mode, to test something... and then later turn the plugin(s) back on.

Closing, as no action required.
