### ISSUE TITLE
Option to click on the note/page containing the dangling link

### ISSUE THREAD

**Issue by candideu** [graydon/obsidian-dangling-links#25]
Hi! Thank you for making this important plugin!

I would like the option of clicking on the note so that I can jump directly to the page and fix the dangling link:

![](https://i.imgur.com/xxLbLy0.png)

**Comment by claremacrae** [comment]
Have you tried clicking on either of the blue, underlined pieces of text just below the filename?

**Comment by candideu** [comment]
Hi @claremacrae! For some reason, I thought clicking on those links would turn them into pages? Good to know that it's just an anchor link.

**Comment by candideu** [comment]
Hi @claremacrae! For some reason, I thought clicking on those links would turn them into pages? Good to know that it's just an anchor link. 

I might make a PR to the README, under Usage, to clarify/explain this.

**Comment by claremacrae** [comment]
@candideu I'm just a user of the plugin, so have no opinion on the README, but just to note, I think the behaviour of the blue text is reasonably clear in the GIF there.
