### ISSUE TITLE
Feature request: Exclude dangling links in specified folder

### ISSUE THREAD

**Issue by TSSlade** [graydon/obsidian-dangling-links#3]
I know the idea of folders in some sense runs counter to the ethos of tools like Obsidian, but in my case I try to keep e.g. date notes (2020-12-12.md) and an overall calendar.md note segregated from everything else in a `calendar` folder.

Right now, my list of dangling links is overwhelmed by the vast number of date notes for future dates in calendar 2021 that I don't have any content for yet. That's accurate, but it also diminishes the utility of the plugin by pulling forward tons of noise.

**Comment by santiyounger** [comment]
This would be amazing, I have a similar request, where this would be the initial step to make it work
thank you

**Comment by justinobney** [comment]
I would also love to see a setting for "excluded folders". I am just getting into PKM and am on a "reset" of my first attempt. Part of that means I put a bunch of stuff into an "Archive" folder. I would love to exclude dangling links in the archive folder.

**Comment by flip-md** [comment]
Is addressed in https://github.com/graydon/obsidian-dangling-links/pull/7 and hopefully merged soon :)

**Comment by graydon** [comment]
Merged and released in 0.3.0
