### ISSUE TITLE
Feature request to add dangling headers

### ISSUE THREAD

**Issue by tyson-nw** [graydon/obsidian-dangling-links#6]
As I fill out a note I will add `[[#headername]]` for headers I need to fill out later. It would be great if I could get a pane that includes dangling header links as well for the currently selected note. Maybe in a second tab.

Anyway, thank you for the plugin it is a lifesaver.

**Comment by claremacrae** [comment]
There is a new community plugin [Broken Links](https://github.com/ipshing/obsidian-broken-links) that has just been released, and that contains a number of features that this Dangling Links plugin does not.

I've been using Broken Links for a few days now, and it is excellent. The two plugins also play nicely together.

So I'm closing as 'wont do' any requests for facilities in Dangling Links that Broken Links already provides.
