### ISSUE TITLE
Collapse all links in the list

### ISSUE THREAD

**Issue by Taitava** [graydon/obsidian-dangling-links#9]
Hi!

I just installed your plugin and I like it :). I have a lot of dangling links and I noticed that initially all the links are expanded in the list, so I collapsed each one of them one by one to make more links visible at one glance (I use the "Group by dangling link" mode). Can you create a button for collapsing all links? (And if the button gets pressed again, it could expand all links again).

Or is there another way to do this?

Thank you :).

**Comment by claremacrae** [comment]
Hi @Taitava, I see you've logged a few requests around helping to manage with large numbers of dangling links.

What sort of quantity were you regarding as "large"? Tens, hundreds, thousands?

And have you since been able to fix them and get them under control?

**Comment by Taitava** [comment]
Hi @claremacrae ! 🙂 

Currently, I have 450 dangling links in one vault. I have just manually collapsed all of them every time I've encountered new links in the dangling links panel.

**Comment by claremacrae** [comment]
> Hi @claremacrae ! 🙂
> 
> Currently, I have 450 dangling links in one vault. I have just manually collapsed all of them every time I've encountered new links in the dangling links panel.

Hi @Taitava,

Good grief!! I'll reply in your other message where you give more detail - thanks.

**Comment by claremacrae** [comment]
There is a new community plugin [Broken Links](https://github.com/ipshing/obsidian-broken-links) that has just been released, and that contains a number of features that this Dangling Links plugin does not.

I've been using Broken Links for a few days now, and it is excellent. The two plugins also play nicely together.

So I'm closing as 'wont do' any requests for facilities in Dangling Links that Broken Links already provides.
